
/* This file was generated automatically by Zephir do not modify it! */

#ifndef ZEPHIR_CLASS_ENTRIES_H
#define ZEPHIR_CLASS_ENTRIES_H

#include "phalconry/exception.zep.h"
#include "phalconry/http/client/adapter/adapterinterface.zep.h"
#include "phalconry/http/client/message.zep.h"
#include "phalconry/mvc/applicationawareinterface.zep.h"
#include "phalconry/config.zep.h"
#include "phalconry/http/client/exception.zep.h"
#include "phalconry/mvc/application/bootstrapinterface.zep.h"
#include "phalconry/mvc/application/handlerinterface.zep.h"
#include "phalconry/mvc/applicationinterface.zep.h"
#include "phalconry/mvc/environmentinterface.zep.h"
#include "phalconry/mvc/module/managerinterface.zep.h"
#include "phalconry/mvc/moduleinterface.zep.h"
#include "phalconry/mvc/plugin/managerinterface.zep.h"
#include "phalconry/mvc/plugininterface.zep.h"
#include "phalconry/webservice/serviceinterface.zep.h"
#include "phalconry/di/serviceproviderinterface.zep.h"
#include "phalconry/events/globalmanager.zep.h"
#include "phalconry/http/client.zep.h"
#include "phalconry/http/client/adapter/curl.zep.h"
#include "phalconry/http/client/adapter/exception.zep.h"
#include "phalconry/http/client/adapter/stream.zep.h"
#include "phalconry/http/client/header.zep.h"
#include "phalconry/http/client/request.zep.h"
#include "phalconry/http/client/response.zep.h"
#include "phalconry/http/uri.zep.h"
#include "phalconry/http/util/mimetype.zep.h"
#include "phalconry/mvc/application.zep.h"
#include "phalconry/mvc/application/bootstrap.zep.h"
#include "phalconry/mvc/application/exception.zep.h"
#include "phalconry/mvc/application/handler.zep.h"
#include "phalconry/mvc/env.zep.h"
#include "phalconry/mvc/hmvc/exception.zep.h"
#include "phalconry/mvc/hmvc/request.zep.h"
#include "phalconry/mvc/module.zep.h"
#include "phalconry/mvc/module/manager.zep.h"
#include "phalconry/mvc/plugin.zep.h"
#include "phalconry/mvc/plugin/exception.zep.h"
#include "phalconry/mvc/plugin/manager.zep.h"
#include "phalconry/mvc/responder.zep.h"
#include "phalconry/text.zep.h"
#include "phalconry/vartype.zep.h"
#include "phalconry/webservice/exception.zep.h"
#include "phalconry/webservice/factory.zep.h"
#include "phalconry/webservice/manager.zep.h"
#include "phalconry/webservice/service.zep.h"

#endif